Safeguards to ensure a more stable cross-compile path for 'Windows bundles'

diff --git a/buildscripts/build_windows_mcxtrace_conda b/buildscripts/build_windows_mcxtrace_conda
--- a/buildscripts/build_windows_mcxtrace_conda
+++ b/buildscripts/build_windows_mcxtrace_conda
@@ -29,7 +29,7 @@ if [ "x$2" != "x" ]; then
     sed s/@FLAVOR@/mcxtrace/g docupdate.bat.in.3 > docupdate.bat
 
     sed s/@VERSION@/${1}/g McXtrace-metapackage64-MSVC.iss > McXtrace-${1}-metapackage64-MSVC.iss
-    ./iscc McXtrace-${1}-metapackage64-MSVC.iss
+    ./iscc McXtrace-${1}-metapackage64-MSVC.iss || { echo "ERROR: Inno Setup compilation of McXtrace-${1}-metapackage64-MSVC.iss failed" >&2; exit 1; }
     mv Output/McXtrace-Metapackage-${1}-MSVC-win64.exe dist/
     cp $WORK/INSTALL-McXtrace/Windows/README.md dist/
 fi
