Comment for debugging

diff --git a/.github/workflows/mcstas-conda-basictest.yml b/.github/workflows/mcstas-conda-basictest.yml
--- a/.github/workflows/mcstas-conda-basictest.yml
+++ b/.github/workflows/mcstas-conda-basictest.yml
@@ -22,7 +22,6 @@ jobs:
           - { os: ubuntu-latest, python: '3.12', mpi: 'mpich' }
           - { os: macos-latest, python: '3.12', mpi: 'openmpi' }
           - { os: macos-latest, python: '3.12', mpi: 'mpich' }
-          #- { os: windows-latest, python: '3.12', mpi: 'msmpi' }
 
     name: ${{ matrix.os }}.${{ matrix.mpi }}.python-${{ matrix.python }}
     runs-on: ${{ matrix.os }}
@@ -116,243 +115,243 @@ jobs:
               false
            fi
 
-    - name: Launch BNL_H8 instrument
-      id: h8-test
-      if: runner.os != 'Windows'
-      # Status: Works on Unixes
-      run: |
-           set -e
-           set -u
-           set -x
-           test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
-           ${MCSTAS_EXECUTABLE} --version
-           mctest --instr=BNL_H8 --testdir=run_singletests
+    # - name: Launch BNL_H8 instrument
+    #   id: h8-test
+    #   if: runner.os != 'Windows'
+    #   # Status: Works on Unixes
+    #   run: |
+    #        set -e
+    #        set -u
+    #        set -x
+    #        test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
+    #        ${MCSTAS_EXECUTABLE} --version
+    #        mctest --instr=BNL_H8 --testdir=run_singletests
 
-    - name: Launch BNL_H8 instrument (MPI)
-      id: h8-test-mpi
-      if: runner.os != 'Windows'
-      # Status: Works on Unixes
-      run: |
-           set -e
-           set -u
-           set -x
-           test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
-           ${MCSTAS_EXECUTABLE} --version
-           mctest --instr=BNL_H8 --mpi=2 --testdir=run_singletests
+    # - name: Launch BNL_H8 instrument (MPI)
+    #   id: h8-test-mpi
+    #   if: runner.os != 'Windows'
+    #   # Status: Works on Unixes
+    #   run: |
+    #        set -e
+    #        set -u
+    #        set -x
+    #        test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
+    #        ${MCSTAS_EXECUTABLE} --version
+    #        mctest --instr=BNL_H8 --mpi=2 --testdir=run_singletests
 
-    - name: Launch MCPL test instrument
-      id: mcpl-test
-      if: runner.os != 'Windows'
-      # Status: Works on Unixes
-      run: |
-           set -e
-           set -u
-           set -x
-           test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
-           ${MCSTAS_EXECUTABLE} --version
-           mctest --instr=ESS_BEER_MCPL --testdir=run_singletests
+    # - name: Launch MCPL test instrument
+    #   id: mcpl-test
+    #   if: runner.os != 'Windows'
+    #   # Status: Works on Unixes
+    #   run: |
+    #        set -e
+    #        set -u
+    #        set -x
+    #        test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
+    #        ${MCSTAS_EXECUTABLE} --version
+    #        mctest --instr=ESS_BEER_MCPL --testdir=run_singletests
 
-    - name: Launch MCPL test instrument (mpi)
-      id: mcpl-test-mpi
-      if: runner.os != 'Windows'
-      # Status: Works on Unixes
-      run: |
-           set -e
-           set -u
-           set -x
-           test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
-           ${MCSTAS_EXECUTABLE} --version
-           mctest --instr=ESS_BEER_MCPL --mpi=2 --testdir=run_singletests
-
-
-
-    - name: Launch NCrystal test instrument
-      id: ncrystal-test
-      if: runner.os != 'Windows'
-      # Status: Works on Unixes
-      run: |
-           set -e
-           set -u
-           set -x
-           test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
-           ${MCSTAS_EXECUTABLE} --version
-           mctest --instr=NCrystal_example --testdir=run_singletests
-
-    - name: Launch NCrystal test instrument (mpi)
-      id: ncrystal-test-mpi
-      if: runner.os != 'Windows'
-      # Status: Works on Unixes
-      run: |
-           set -e
-           set -u
-           set -x
-           test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
-           ${MCSTAS_EXECUTABLE} --version
-           mctest --instr=NCrystal_example --mpi=2 --testdir=run_singletests
-
-    - name: Launch NeXus test instrument
-      id: nexus-test
-     if: runner.os != 'Windows'
-      # Status: Works on Unixes
-      run: |
-           set -e
-           set -u
-           set -x
-           test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
-           ${MCSTAS_EXECUTABLE} --version
-           mctest --instr=templateSANS_Mantid --testdir=run_singletests
-           mctest --instr=templateSANS_Mantid --mpi=2 --testdir=run_singletests
+    # - name: Launch MCPL test instrument (mpi)
+    #   id: mcpl-test-mpi
+    #   if: runner.os != 'Windows'
+    #   # Status: Works on Unixes
+    #   run: |
+    #        set -e
+    #        set -u
+    #        set -x
+    #        test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
+    #        ${MCSTAS_EXECUTABLE} --version
+    #        mctest --instr=ESS_BEER_MCPL --mpi=2 --testdir=run_singletests
 
 
-    - name: Check for modified instruments
-      id: instr-test
-      run: |
-           set -e
-           set -u
-           set -x
-           export TMPDIR=/tmp
-           export MCSTAS_EXECUTABLE="mcstas"
-           export MCRUN_EXECUTABLE="mcrun"
-           export MCTEST_EXECUTABLE="mctest"
-           export PATH=${PATH}:${PWD}/install_mcstas/bin/:${PWD}/install_mcstas/mcstas/3.99.99/bin/
-           # Check if any instr files were modified during last commit
-           cd src
-           export CHANGEDCOMPS=`git diff --name-only HEAD HEAD~1| grep \.comp\$ | grep mcstas-comps | xargs -n1 basename | sed s/\.comp//g | xargs echo`
-           export NUMCHANGEDCOMPS=`git diff --name-only HEAD HEAD~1|grep \.comp\$ | grep mcstas-comps | wc -l | xargs echo`
-           export COMPILIST=""
-           export RUNALL="NO"
-           if [ "$NUMCHANGEDCOMPS" != "0" ];
-           then
-             if [ "$NUMCHANGEDCOMPS" -lt "10" ];
-             then
-               for comp in $CHANGEDCOMPS;
-               do
-                 echo Finding instruments matching component $comp
-                 MATCH=`find mcstas-comps -name \*.instr -exec grep -H ${comp} \{\} \; | cut -f1 -d: | sort | uniq | xargs -n1 basename | sed s/\.instr//g | xargs echo`
-                 export COMPILIST=`echo $COMPILIST $MATCH`
-               done
-             else
-               export RUNALL="YES"
-             fi
-           fi
-           export CHANGEDINSTR=`git diff --name-only HEAD HEAD~1| grep \.instr\$ | grep mcstas-comps | xargs -n1 basename | sed s/\.instr//g | xargs echo`
-           export CHANGEDINSTR=`echo $CHANGEDINSTR $COMPILIST | sort | uniq | sed s/\ /,/g`
-           export NUMCHANGEDINSTR=`git diff --name-only HEAD HEAD~1|grep \.instr\$ | grep mcstas-comps | wc -l | xargs echo`
-           echo ----
-           echo $NUMCHANGEDCOMPS components and $NUMCHANGEDINSTR instruments were changed, resulting in this list:
-           echo $CHANGEDINSTR
-           echo ----
-           cd -
-           if [ "$NUMCHANGEDINSTR" -gt "10" ];
-           then
-             export RUNALL="YES"
-           fi
-           export PERMISSIVE=" "
-           if [ "$NUMCHANGEDINSTR" != "0" ] || [ "$NUMCHANGEDCOMPS" != "0" ];
-           then
-             if [ "$RUNALL" == "NO" ];
-             then
-               export SCOPE="--instr=$CHANGEDINSTR"
-             else
-               export SCOPE=" "
-             fi
-             if [ "$RUNNER_OS" != "Windows" ]; then
-               mkdir run_mctest && cd run_mctest
-               if [ "$RUNNER_OS" == macOS ]; then
-                 export PERMISSIVE="--permissive"
-               fi
-               ${MCTEST_EXECUTABLE} --testdir $PWD $SCOPE --suffix=CHANGES $PERMISSIVE
-               mcviewtest --nobrowse $PWD
-             else
-               echo mctest --verbose --testdir=. $SCOPE --suffix=CHANGES --permissive > changedinstr.bat
-             fi
-           fi
 
-    # END of Unix tests
+    # - name: Launch NCrystal test instrument
+    #   id: ncrystal-test
+    #   if: runner.os != 'Windows'
+    #   # Status: Works on Unixes
+    #   run: |
+    #        set -e
+    #        set -u
+    #        set -x
+    #        test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
+    #        ${MCSTAS_EXECUTABLE} --version
+    #        mctest --instr=NCrystal_example --testdir=run_singletests
 
-    - name: Run modified instruments Win
-      id: instr-test-Win
-      if: runner.os == 'Windows' # Windows only
-      shell: cmd
-      run: |
-        if exist changedinstr.bat (
-          mkdir run_mctest
-          cd run_mctest
-          call ..\changedinstr.bat
-        )
+    # - name: Launch NCrystal test instrument (mpi)
+    #   id: ncrystal-test-mpi
+    #   if: runner.os != 'Windows'
+    #   # Status: Works on Unixes
+    #   run: |
+    #        set -e
+    #        set -u
+    #        set -x
+    #        test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
+    #        ${MCSTAS_EXECUTABLE} --version
+    #        mctest --instr=NCrystal_example --mpi=2 --testdir=run_singletests
 
-    # Start of Windows tests
-    - name: Prepare rundirs Windows
-      if: runner.os == 'Windows' # Windows only
-      shell: cmd
-      run: mkdir run_rng run_std run_mcpl_output run_mcpl_input run_mcpl_input_once run_union run_ncrystal
+    # - name: Launch NeXus test instrument
+    #   id: nexus-test
+    #  if: runner.os != 'Windows'
+    #   # Status: Works on Unixes
+    #   run: |
+    #        set -e
+    #        set -u
+    #        set -x
+    #        test -f ${CONDA_PREFIX}/bin/${MCSTAS_EXECUTABLE}
+    #        ${MCSTAS_EXECUTABLE} --version
+    #        mctest --instr=templateSANS_Mantid --testdir=run_singletests
+    #        mctest --instr=templateSANS_Mantid --mpi=2 --testdir=run_singletests
 
-    - name: Prepare and run rng instrument Windows
-      if: runner.os == 'Windows' # Windows only
-      shell: cmd
-      working-directory: run_rng
-      run: |
-        copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_RNG\Test_RNG_rand01\Test_RNG_rand01.instr test.instr
-        %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 Ncount=1000 -d RNGtest
 
-    - name: Prepare and run BNL_H8 instrument Windows
-      if: runner.os == 'Windows' # Windows only
-      shell: cmd
-      working-directory: run_std
-      run: |
-        copy %CONDA_PREFIX%\share\mcstas\resources\examples\BNL\BNL_H8\BNL_H8.instr test.instr
-        %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 -y
+    # - name: Check for modified instruments
+    #   id: instr-test
+    #   run: |
+    #        set -e
+    #        set -u
+    #        set -x
+    #        export TMPDIR=/tmp
+    #        export MCSTAS_EXECUTABLE="mcstas"
+    #        export MCRUN_EXECUTABLE="mcrun"
+    #        export MCTEST_EXECUTABLE="mctest"
+    #        export PATH=${PATH}:${PWD}/install_mcstas/bin/:${PWD}/install_mcstas/mcstas/3.99.99/bin/
+    #        # Check if any instr files were modified during last commit
+    #        cd src
+    #        export CHANGEDCOMPS=`git diff --name-only HEAD HEAD~1| grep \.comp\$ | grep mcstas-comps | xargs -n1 basename | sed s/\.comp//g | xargs echo`
+    #        export NUMCHANGEDCOMPS=`git diff --name-only HEAD HEAD~1|grep \.comp\$ | grep mcstas-comps | wc -l | xargs echo`
+    #        export COMPILIST=""
+    #        export RUNALL="NO"
+    #        if [ "$NUMCHANGEDCOMPS" != "0" ];
+    #        then
+    #          if [ "$NUMCHANGEDCOMPS" -lt "10" ];
+    #          then
+    #            for comp in $CHANGEDCOMPS;
+    #            do
+    #              echo Finding instruments matching component $comp
+    #              MATCH=`find mcstas-comps -name \*.instr -exec grep -H ${comp} \{\} \; | cut -f1 -d: | sort | uniq | xargs -n1 basename | sed s/\.instr//g | xargs echo`
+    #              export COMPILIST=`echo $COMPILIST $MATCH`
+    #            done
+    #          else
+    #            export RUNALL="YES"
+    #          fi
+    #        fi
+    #        export CHANGEDINSTR=`git diff --name-only HEAD HEAD~1| grep \.instr\$ | grep mcstas-comps | xargs -n1 basename | sed s/\.instr//g | xargs echo`
+    #        export CHANGEDINSTR=`echo $CHANGEDINSTR $COMPILIST | sort | uniq | sed s/\ /,/g`
+    #        export NUMCHANGEDINSTR=`git diff --name-only HEAD HEAD~1|grep \.instr\$ | grep mcstas-comps | wc -l | xargs echo`
+    #        echo ----
+    #        echo $NUMCHANGEDCOMPS components and $NUMCHANGEDINSTR instruments were changed, resulting in this list:
+    #        echo $CHANGEDINSTR
+    #        echo ----
+    #        cd -
+    #        if [ "$NUMCHANGEDINSTR" -gt "10" ];
+    #        then
+    #          export RUNALL="YES"
+    #        fi
+    #        export PERMISSIVE=" "
+    #        if [ "$NUMCHANGEDINSTR" != "0" ] || [ "$NUMCHANGEDCOMPS" != "0" ];
+    #        then
+    #          if [ "$RUNALL" == "NO" ];
+    #          then
+    #            export SCOPE="--instr=$CHANGEDINSTR"
+    #          else
+    #            export SCOPE=" "
+    #          fi
+    #          if [ "$RUNNER_OS" != "Windows" ]; then
+    #            mkdir run_mctest && cd run_mctest
+    #            if [ "$RUNNER_OS" == macOS ]; then
+    #              export PERMISSIVE="--permissive"
+    #            fi
+    #            ${MCTEST_EXECUTABLE} --testdir $PWD $SCOPE --suffix=CHANGES $PERMISSIVE
+    #            mcviewtest --nobrowse $PWD
+    #          else
+    #            echo mctest --verbose --testdir=. $SCOPE --suffix=CHANGES --permissive > changedinstr.bat
+    #          fi
+    #        fi
 
-    - name: Prepare and run NCrystal instrument Windows
-      if: runner.os == 'Windows' # Windows only
-      shell: cmd
-      working-directory: run_ncrystal
-      run: |
-        copy %CONDA_PREFIX%\share\mcstas\resources\examples\NCrystal\NCrystal_example\NCrystal_example.instr test.instr
-        %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 -y
+    # # END of Unix tests
 
-    - name: Prepare and run MCPL_input instrument Windows
-      if: runner.os == 'Windows' # Windows only
-      shell: cmd
-      working-directory: run_mcpl_input
-      run: |
-        copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_MCPL_etc\Test_MCPL_input\Test_MCPL_input.instr test.instr
-        copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_MCPL_etc\Test_MCPL_input\voutput.mcpl.gz .
-        %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 -y
+    # - name: Run modified instruments Win
+    #   id: instr-test-Win
+    #   if: runner.os == 'Windows' # Windows only
+    #   shell: cmd
+    #   run: |
+    #     if exist changedinstr.bat (
+    #       mkdir run_mctest
+    #       cd run_mctest
+    #       call ..\changedinstr.bat
+    #     )
 
-    - name: Prepare and run MCPL_input_once instrument Windows
-      if: runner.os == 'Windows' # Windows only
-      shell: cmd
-      working-directory: run_mcpl_input_once
-      run: |
-        copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_MCPL_etc\Test_MCPL_input_once\Test_MCPL_input_once.instr test.instr
-        copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_MCPL_etc\Test_MCPL_input_once\voutput.mcpl.gz .
-        %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 -y
+    # # Start of Windows tests
+    # - name: Prepare rundirs Windows
+    #   if: runner.os == 'Windows' # Windows only
+    #   shell: cmd
+    #   run: mkdir run_rng run_std run_mcpl_output run_mcpl_input run_mcpl_input_once run_union run_ncrystal
 
-    - name: Prepare and run MCPL_output instrument Windows
-      if: runner.os == 'Windows' # Windows only
-      shell: cmd
-      working-directory: run_mcpl_output
-      run: |
-        copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_MCPL_etc\Test_MCPL_output\Test_MCPL_output.instr test.instr
-        %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 -y
+    # - name: Prepare and run rng instrument Windows
+    #   if: runner.os == 'Windows' # Windows only
+    #   shell: cmd
+    #   working-directory: run_rng
+    #   run: |
+    #     copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_RNG\Test_RNG_rand01\Test_RNG_rand01.instr test.instr
+    #     %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 Ncount=1000 -d RNGtest
 
-    - name: Test RNG instrument output Windows
-      if: runner.os == 'Windows' # Windows only
-      working-directory: run_rng
-      shell: bash
-      run:   |
-        export SUM=`grep -v \# RNGtest/rngout.dat | dos2unix | md5sum | cut -f1 -d\ `
-        export EXPECTED="f192ce4609e2225bf9d42ce9c5fa5a86"
-        if [ "${EXPECTED}" == "${SUM}" ];
-        then
-          echo RNG test success!
-          true
-        else
-          echo RNG test failure!
-          false
-        fi
-    # END of Windows tests
+    # - name: Prepare and run BNL_H8 instrument Windows
+    #   if: runner.os == 'Windows' # Windows only
+    #   shell: cmd
+    #   working-directory: run_std
+    #   run: |
+    #     copy %CONDA_PREFIX%\share\mcstas\resources\examples\BNL\BNL_H8\BNL_H8.instr test.instr
+    #     %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 -y
+
+    # - name: Prepare and run NCrystal instrument Windows
+    #   if: runner.os == 'Windows' # Windows only
+    #   shell: cmd
+    #   working-directory: run_ncrystal
+    #   run: |
+    #     copy %CONDA_PREFIX%\share\mcstas\resources\examples\NCrystal\NCrystal_example\NCrystal_example.instr test.instr
+    #     %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 -y
+
+    # - name: Prepare and run MCPL_input instrument Windows
+    #   if: runner.os == 'Windows' # Windows only
+    #   shell: cmd
+    #   working-directory: run_mcpl_input
+    #   run: |
+    #     copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_MCPL_etc\Test_MCPL_input\Test_MCPL_input.instr test.instr
+    #     copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_MCPL_etc\Test_MCPL_input\voutput.mcpl.gz .
+    #     %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 -y
+
+    # - name: Prepare and run MCPL_input_once instrument Windows
+    #   if: runner.os == 'Windows' # Windows only
+    #   shell: cmd
+    #   working-directory: run_mcpl_input_once
+    #   run: |
+    #     copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_MCPL_etc\Test_MCPL_input_once\Test_MCPL_input_once.instr test.instr
+    #     copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_MCPL_etc\Test_MCPL_input_once\voutput.mcpl.gz .
+    #     %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 -y
+
+    # - name: Prepare and run MCPL_output instrument Windows
+    #   if: runner.os == 'Windows' # Windows only
+    #   shell: cmd
+    #   working-directory: run_mcpl_output
+    #   run: |
+    #     copy %CONDA_PREFIX%\share\mcstas\resources\examples\Tests_MCPL_etc\Test_MCPL_output\Test_MCPL_output.instr test.instr
+    #     %CONDA_PREFIX%\bin\mcrun --verbose test.instr -s1000 -y
+
+    # - name: Test RNG instrument output Windows
+    #   if: runner.os == 'Windows' # Windows only
+    #   working-directory: run_rng
+    #   shell: bash
+    #   run:   |
+    #     export SUM=`grep -v \# RNGtest/rngout.dat | dos2unix | md5sum | cut -f1 -d\ `
+    #     export EXPECTED="f192ce4609e2225bf9d42ce9c5fa5a86"
+    #     if [ "${EXPECTED}" == "${SUM}" ];
+    #     then
+    #       echo RNG test success!
+    #       true
+    #     else
+    #       echo RNG test failure!
+    #       false
+    #     fi
+    # # END of Windows tests
 
     - name: 'Tar output files'
       id: tar-package
