mpi=auto in McXtrace and rename "combined" ->  changes

diff --git a/.github/workflows/mcxtrace-basictest.yml b/.github/workflows/mcxtrace-basictest.yml
--- a/.github/workflows/mcxtrace-basictest.yml
+++ b/.github/workflows/mcxtrace-basictest.yml
@@ -365,7 +365,7 @@ jobs:
            test -n "$(command -v mcxtrace${EXESUFFIX})"
            mcxtrace${EXESUFFIX} --version
            mxtest${SUFFIX} --instr=JJ_SAXS,ESRF_BM29,Test_MCPL_input,Test_MCPL_output,Test_Absorption --testdir=run_basictests --suffix=${{ matrix.method }}
-           mxtest${SUFFIX} --mpi=2 --instr=JJ_SAXS,ESRF_BM29,Test_MCPL_input,Test_MCPL_output,Test_Absorption --testdir=run_basictests --suffix=${{ matrix.method }}_${{ matrix.mpi }}
+           mxtest${SUFFIX} --mpi=auto --instr=JJ_SAXS,ESRF_BM29,Test_MCPL_input,Test_MCPL_output,Test_Absorption --testdir=run_basictests --suffix=${{ matrix.method }}_${{ matrix.mpi }}
 
     - name: Check for modified instruments
       id: instr-test
@@ -421,7 +421,7 @@ jobs:
                  NUMMATCH=`find src/mcxtrace-comps -name \*.instr -exec grep -H ${comp} \{\} \; | cut -f1 -d: | sort | uniq | wc -l`
                  if [ "$NUMMATCH" -gt "0" ];
                  then
-                   ${MXTEST_EXECUTABLE} --mpi=2 --testdir run_mxtest --comp=${comp} --suffix=CHANGES_${comp}_${{ matrix.method }}_${{ matrix.CC || 'default' }}_${{ matrix.mpi }} $PERMISSIVE --verbose || { echo "${MXTEST_EXECUTABLE} failed with exit code $?"; exit 1; }
+                   ${MXTEST_EXECUTABLE} --mpi=auto --testdir run_mxtest --comp=${comp} --suffix=CHANGES_${comp}_${{ matrix.method }}_${{ matrix.CC || 'default' }}_${{ matrix.mpi }} $PERMISSIVE --verbose || { echo "${MXTEST_EXECUTABLE} failed with exit code $?"; exit 1; }
                  else
                    echo No matching tests found
                  fi
@@ -547,12 +547,12 @@ jobs:
              artifact_name=$(basename "$(dirname "$tgz")")
 
              if [ -d "$work"/run_mxtest/ ]; then
-               mkdir -p combined
+               mkdir -p changes
                for labeldir in "$work"/run_mxtest/*/; do
                  if [[ "$artifact_name" == *"ubuntu-latest"* ]]; then
                    REFLABEL=$(basename "$labeldir")
                  fi
-                 mv $labeldir combined/
+                 mv $labeldir changes/
                done
              fi
 
@@ -580,8 +580,8 @@ jobs:
            set -e
            set -u
            set -x
-           if [ -d combined/ ]; then
-             cd combined
+           if [ -d changes/ ]; then
+             cd changes
              if [ -z "$REFLABEL" ]; then
                mxviewtest --reflabel "$REFLABEL" --nobrowse
              else
@@ -593,11 +593,11 @@ jobs:
              cd basictests && mxviewtest --nobrowse && ls -l $PWD && cd -
            fi
 
-    - name: 'Tar combined output (all platform folders + comparison table)'
+    - name: 'Tar output (all platform folders + comparison tables)'
       id: tar-package
       run: |
-           if [ -d combined/ ]; then
-             tar cvfz mcxtrace-basictest-comparison.tgz combined basictests
+           if [ -d changes/ ]; then
+             tar cvfz mcxtrace-basictest-comparison.tgz changes basictests
            else
              tar cvfz mcxtrace-basictest-comparison.tgz basictests
            fi
